version: "3.8"
services:

  db:
    image: postgres:latest
    networks:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgres/data

  backend:
    depends_on:
      - db
    image: ap-test-backend:latest
    build: ./backend
    restart: always
    networks:
      - db
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env

volumes:
  pgdata:
    name: pgdata

networks:
  db:
    name: db
